# .github/workflows/check-wiki-update.yml
name: Check spacemit-com/linux Wiki Updates

on:
  schedule:
    - cron: '0 * * * *'   # every hour
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  check-wiki:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.check.outputs.updated }}
      ts:      ${{ steps.check.outputs.ts }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone the spacemit-com/linux wiki
        run: |
          git clone https://github.com/spacemit-com/linux.wiki.git wiki
          cd wiki
          git log -1 --format="%ct" > ../latest_timestamp.txt

      - name: Load previous timestamp (or zero)
        id: load-prev
        run: |
          if [[ -f .wiki_timestamp ]]; then
            echo "prev_ts=$(cat .wiki_timestamp)" >> $GITHUB_OUTPUT
          else
            echo "prev_ts=0" >> $GITHUB_OUTPUT
          fi

      - name: Compare timestamps
        id: check
        run: |
          latest_ts=$(cat latest_timestamp.txt)
          prev_ts=${{ steps.load-prev.outputs.prev_ts }}

          echo "latest=$latest_ts"  >> $GITHUB_OUTPUT
          echo "previous=$prev_ts"  >> $GITHUB_OUTPUT

          if (( latest_ts > prev_ts )); then
            ts=$(date -u -d "@$latest_ts" +"%Y-%m-%dT%H:%M:%SZ")
            echo "updated=true"    >> $GITHUB_OUTPUT
            echo "ts=$ts"          >> $GITHUB_OUTPUT
            # Overwrite and force-add even if ignored
            echo "$latest_ts"      > .wiki_timestamp
          else
            echo "updated=false"   >> $GITHUB_OUTPUT
          fi

      - name: Persist .wiki_timestamp
        if: steps.check.outputs.updated == 'true'
        run: |
          git add -f .wiki_timestamp
          git commit -m "chore: record last wiki update timestamp (${{ steps.check.outputs.ts }})"
          git push

  create-issue-if-update:
    needs: check-wiki
    runs-on: ubuntu-latest
    if: needs.check-wiki.outputs.updated == 'true'

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Create Issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: |
            spacemit-com/linux/wiki updated at ${{ needs.check-wiki.outputs.ts }}
          labels: wiki-update
          body: |
            The [spacemit-com/linux wiki](https://github.com/spacemit-com/linux/wiki) was updated on **${{ needs.check-wiki.outputs.ts }}**.

            You can view the latest run here:  
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            > *This issue was created automatically by GitHub Actions.*
